### ISSUE TITLE
extractLdesMetadata function cannot extract the metadata.

### ISSUE THREAD

**Issue by argahsuknesib** [woutslabbinck/VersionAwareLDESinLDP#32]
```ts
import { extractLdesMetadata, LDESinLDP, LDPCommunication } from "@treecg/versionawareldesinldp";

async function main() {
    const ldes_url: string = 'http://localhost:3000/dataset_participant1/data/';
    const communication = new LDPCommunication();
    const ldes_in_ldp = new LDESinLDP(ldes_url, communication);
    const metadata = await ldes_in_ldp.readMetadata();
    console.log(extractLdesMetadata(metadata, ldes_url))
}

main();
```

this gives the output in the console,

```bash
/home/kush/Code/Forks/VersionAwareLDESinLDP/dist/util/LdesUtil.js:38
        throw Error("Could not extract LDES metadata for ".concat(ldesIdentifier, "."));
              ^
Error: Could not extract LDES metadata for http://localhost:3000/dataset_participant1/data/.
    at extractLdesMetadata (/home/kush/Code/Forks/VersionAwareLDESinLDP/dist/util/LdesUtil.js:38:15)
    at /home/kush/Code/solid-stream-aggregator/src/utils/authentication/ldes-readMetadata.ts:8:36
    at Generator.next (<anonymous>)
    at fulfilled (/home/kush/Code/solid-stream-aggregator/src/utils/authentication/ldes-readMetadata.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```
which should not be the case as the LDES in LDP URL is valid.
What do you think could be wrong?

CC : @svrstich

**Comment by woutslabbinck** [comment]
I've tried to run your code and the first error I get is that the resource was not found, (which is logical as it was not initialised on my machine).

I've set up a CSS and then I've added the following so it could be run:
```js
import { extractLdesMetadata, LDESinLDP, LDPCommunication } from "@treecg/versionawareldesinldp";

async function main() {
    const ldes_url: string = 'http://localhost:3000/dataset_participant1/data/';
    const communication = new LDPCommunication();
    const ldes_in_ldp = new LDESinLDP(ldes_url, communication);

    await ldes_in_ldp.initialise({treePath:"http://purl.org/dc/terms/created"})
    const metadata = await ldes_in_ldp.readMetadata();
    console.log(extractLdesMetadata(metadata, ldes_url))
}

main();
```

Still, I got the same error so I looked into why exactly the util method `extractLdesMetadata` is failing.
 It failed due to the following error: `Error: Found 0 timestampProperties for http://localhost:3000/dataset_participant1/data/#EventStream, only expected one`

This means that the method only works with version aware initialised LDES in LDPs and will thus never work if there are no timestamppaths.

There are however two ways to overcome this error.

Option 1: Use the new LDES (in LDP) metadata parsers (e.g.): 

```js
import { extractLdesMetadata,MetadataParser, LDESinLDP, LDPCommunication } from "@treecg/versionawareldesinldp";
async function main() {
    const ldes_url: string = 'http://localhost:3000/dataset_participant1/data/';
    const communication = new LDPCommunication();
    const ldes_in_ldp = new LDESinLDP(ldes_url, communication);
    await ldes_in_ldp.initialise({treePath:"http://purl.org/dc/terms/created"})

    const metadata = await ldes_in_ldp.readMetadata();
    console.log(MetadataParser.extractLDESinLDPMetadata(metadata))
}

main();
```

Option 2: Always initialise with version aware ldes in ldp (although it is not one)
```js
import { extractLdesMetadata,VersionAwareLDESinLDP, LDESinLDP, LDPCommunication } from "@treecg/versionawareldesinldp";
async function main() {
    const ldes_url: string = 'http://localhost:3000/dataset_participant1/data/';
    const communication = new LDPCommunication();
    const ldes_in_ldp = new LDESinLDP(ldes_url, communication);
    const vlil = new VersionAwareLDESinLDP(ldes_in_ldp)
    await vlil.initialise()
    const metadata = await ldes_in_ldp.readMetadata();
    console.log(extractLdesMetadata(metadata, ldes_url + "#EventStream"))
    console.log(MetadataParser.extractLDESinLDPMetadata(metadata))
}

main();
```

**Comment by argahsuknesib** [comment]
Thanks for the detailed explaination @woutslabbinck !
